version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=PSA
      - POSTGRES_USER=Joey
      - POSTGRES_PASSWORD=Password
    ports:
      - "5435:5432"
    networks:
      - postgres

  api:
    build: ./server
    command: npm run start
    environment:
      - PORT=3000
    volumes:
      - ./server:/code
    depends_on:
      - db
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
